[project]
name = "lec08-http"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=2.6.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
